/*
* this is generated by code
*
*  Author: WanQing<1109162935@qq.com>
*/

#ifndef INCLUDE_GRAMMAR__H_
#define INCLUDE_GRAMMAR__H_

typedef enum{
  TS_NIL,
  TS_namelist,
  TS_binop,
  TS_explist,
  TS_exp,
  TS_local_stat,
  TS_global_stat
}TypeStat;

#endif /* INCLUDE_GRAMMAR__H_ */